Feature/add keyboard event
luctst/painperdu pull request #14
Opened 2024-02-13 15:17 UTC by Kvin3324

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!).

2024-02-13 23:52 UTC, luctst requested changes

2024-02-13 23:52 UTC, luctst commented on packages/painperdu/src/components/PainPerdu/painPerdu.tsx
> +function delayForDemo(promise: any) {
Supprimer ça, c'était pour la démo

2024-02-13 23:52 UTC, luctst commented on packages/painperdu/src/components/PainPerduListItemWrapper/PainPerduListItemWrapper.tsx
> +    if (cursor <= 0) return
Il faut ajouter un guard aussi içi qui vérifie qu'on essaye pas de scroll si on est sur le dernier élément de la liste, sinon on a une erreur

2024-02-13 23:52 UTC, luctst commented on packages/painperdu/src/components/PainPerduListItemWrapper/PainPerduListItemWrapper.tsx
> +  const itemsRef:any = useRef<HTMLElement | null>(null)
Pourquoi il y a un `:any` ?

2024-02-13 23:52 UTC, luctst commented on packages/painperdu/src/components/PainPerduSkeleton/PainPerduSkeleton.tsx
Faut refaire le skeleton de manière à ce qu'il ressemble un minimum à l'app parce que la c'était pour tester et ça renvoie une liste d'items faut que ce soit comme sur le modal mais en mode skeleton

2024-02-13 23:52 UTC, luctst commented on packages/painperdu/src/index.css
Il faut qu'on supprime ce fichier le style passe par tailwind

2024-02-14 11:46 UTC, Kvin3324 commented on packages/painperdu/src/index.css
Alors des fois on a besoin d'appliquer nous même du style car y'a pas ce qu'on veut dans tailwind
Sinon on peut ajouter le style directement dans le file où on en a besoin

2024-02-14 11:46 UTC, Kvin3324 commented on packages/painperdu/src/index.css
Et il me semble que tu es obligé de l'avoir pour appliquer le style de tailwind, ça évite d'importer dans les fichiers

2024-02-14 12:08 UTC, Kvin3324 commented on packages/painperdu/src/components/PainPerduListItemWrapper/PainPerduListItemWrapper.tsx
> +    if (cursor <= 0) return
Par contre, faudrait rajouter du code pour bloquer le re-render du compo quand on est en haut ou en bas

2024-02-16 16:29 UTC, luctst approved these changes

2024-02-20 18:33 UTC, merged