Feat/init storybook
luctst/painperdu pull request #2
Opened 2023-11-30 21:53 UTC by Kvin3324

## Feature
Added storybook package && created component to test PainPerdu

J'ai ajouté le package de Storybook, j'ai créé un composant maison, PainPerdu, donc tu me diras ce que tu en penses, surtout niveau config et voir si on peut partir sur la migration du Js en React, si c'est suffisant

2023-12-01 12:29 UTC, luctst requested changes
Alors oui mais les stories pour que ce soit plus clair et plus opti, il faudrait qu'en la config storybook soit seulement dans le packages `painperdu` la ou on va l'utiliser et chaque stories est situé dans le dossier du composant CAD quelque chose comme ça:

```
-| painperdu/
   -| src/
     -| button/
         button.jsx
         button.stories.ts
```

2023-12-01 14:58 UTC, Kvin3324 commented
> Alors oui mais les stories pour que ce soit plus clair et plus opti, il faudrait qu'en la config storybook soit seulement dans le packages `painperdu` la ou on va l'utiliser et chaque stories est situé dans le dossier du composant CAD quelque chose comme ça:
> 
> ```
> -| painperdu/
>    -| src/
>      -| button/
>          button.jsx
>          button.stories.ts
> ```

Je m'étais posé la question mais je suis d'accord avec toi

2023-12-03 10:14 UTC, Kvin3324 commented on packages/painperdu/src/stories/PainPerdu.jsx
J'ai changé le nom du folder pour avoir une structure : 
<img width="290" alt="Capture d’écran 2023-12-03 à 11 13 45" src="https://github.com/luctst/painperdu/assets/29613292/84b1e6a6-5ef2-4930-87df-3e824418fcdc">

Pour aussi répondre à une question : si on avait l'init de Storybook dans le folder `src` , c'est que c'était dans prévu dans leur init et il y a le folder `src` par défaut, c'est dans le file de `main.ts`

2023-12-03 23:53 UTC, luctst commented on packages/painperdu/src/PainPerdu/PainPerdu.stories.js
Faudrait écrire les stories en `.ts` comme ça tu peux tout typer c'est mieux t'as des exemples dans leur doc

2023-12-04 11:08 UTC, luctst commented on packages/painperdu/src/package.json
Mais avant de déclarer la review resolve faut faire la modif 😂

2023-12-04 14:34 UTC, merged